<?php

return [
    'fields' => [
        'location' => 'required|string',
        'meter_id' => 'required|string',
        'meter_details_id' => 'required|numeric',
        'meter_client_acc_no' => 'nullable|string',
        'datetime' => 'date',
        'vrms_a' => 'numeric',
        'vrms_b' => 'numeric',
        'vrms_c' => 'numeric',
        'irms_a' => 'numeric',
        'irms_b' => 'numeric',
        'irms_c' => 'numeric',
        'freq' => 'numeric',
        'pf' => 'numeric',
        'watt' => 'numeric',
        'va' => 'numeric',
        'var' => 'numeric',
        'wh_del' => 'numeric',
        'wh_rec' => 'numeric',
        'wh_net' => 'numeric',
        'wh_total' => 'numeric',
        'varh_neg' => 'numeric',
        'varh_pos' => 'numeric',
        'varh_net' => 'numeric',
        'varh_total' => 'numeric',
        'vah_total' => 'numeric',
        'max_rec_kw_dmd' => 'numeric',
        'max_rec_kw_dmd_time' => 'nullable|date',
        'max_del_kw_dmd' => 'numeric',
        'max_del_kw_dmd_time' => 'nullable|date',
        'max_pos_kvar_dmd' => 'numeric',
        'max_pos_kvar_dmd_time' => 'nullable|date',
        'max_neg_kvar_dmd' => 'numeric',
        'max_neg_kvar_dmd_time' => 'nullable|date',
        'v_ph_angle_a' => 'numeric',
        'v_ph_angle_b' => 'numeric',
        'v_ph_angle_c' => 'numeric',
        'i_ph_angle_a' => 'numeric',
        'i_ph_angle_b' => 'numeric',
        'i_ph_angle_c' => 'numeric',
        'mac_addr' => 'nullable|string',
        'soft_rev' => 'nullable|string',
        'relay_status' => 'integer',
    ],
];
